const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const elements=new Map();
const context={console,setTimeout,clearTimeout,document:{getElementById(id){if(!elements.has(id))elements.set(id,{value:id==='hdfDensity'?'800':'41',addEventListener(){}});return elements.get(id);}}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('optimizer.js','utf8'),context);
vm.runInContext(html.slice(html.indexOf('  <script>')+10,html.lastIndexOf('</script>')),context);
const saved=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const input=saved.result.packages.flatMap(p=>p.items), before=JSON.stringify(input);
const start=Date.now(), packages=context.optimizePackages(input,Number(saved.settings.maxWeight));
assert.equal(JSON.stringify(input),before,'search must not mutate source');
assert.equal(packages.flatMap(p=>p.items).length,input.length);
const signature=items=>items.map(i=>[i.id,Math.min(i.width,i.depth),Math.max(i.width,i.depth),i.height,i.weight].join('|')).sort();
assert.deepEqual(signature(packages.flatMap(p=>p.items)),signature(input));
for(const p of packages){context.validate(p);assert(context.packageWeights(p).total<=p.maxWeight+1e-6);for(const f of p.fillers){assert(!p.items.some(i=>context.boxesOverlap(f,i)));assert(!p.fillers.some(other=>other!==f&&context.boxesOverlap(f,other)));}}
const stats=ps=>({packages:ps.length,volumeLitres:ps.reduce((s,p)=>s+p.baseWidth*p.baseDepth*p.innerHeight/1e6,0),foamLitres:ps.reduce((s,p)=>s+p.fillers.reduce((v,f)=>v+f.width*f.depth*f.height/1e6,0),0),fillers:ps.reduce((s,p)=>s+p.fillers.length,0),details:ps.map(p=>({id:p.id,size:[p.baseWidth,p.baseDepth,p.innerHeight],weight:context.packageWeights(p).total}))});
console.log(JSON.stringify({milliseconds:Date.now()-start,before:stats(saved.result.packages),after:stats(packages)},null,2));
context.saved=saved;
vm.runInContext('result=JSON.parse(JSON.stringify(saved.result)); result.packages[0].locked=true; render=()=>{};show=()=>{};',context);
const lockedBefore=vm.runInContext('JSON.stringify(result.packages[0])',context);
context.repackUnlocked();
assert.equal(vm.runInContext('JSON.stringify(result.packages.find(p=>p.locked))',context),lockedBefore);
assert.equal(vm.runInContext('result.items.length',context),input.length);
console.log('Locked package unchanged; all parts retained.');
vm.runInContext('result=JSON.parse(JSON.stringify(saved.result));',context);
context.document.getElementById('maxWeight').value=saved.settings.maxWeight;
const locks=saved.result.packages.filter(p=>p.locked);
context.repackUnlocked();
const repacked=vm.runInContext('result.packages',context);
for(const locked of locks)assert.equal(JSON.stringify(repacked.find(p=>p.id===locked.id)),JSON.stringify(locked));
console.log('With saved locks:',JSON.stringify(stats(repacked)));
